# NHL Trap Games

Definition: A trap game is about a good team underperforming when they're expected to win

In [1]:
import sys
import os
import polars as pl
from tqdm import tqdm
from typing import List
import pandas as pd
import numpy as np

base_dir = '../'
sys.path.insert(1, base_dir)

import src.config as cfg
import src.utils as utils
import src.sportsipy_utils as sportsipy_utils

## Pull Schedule for Each NHL Team

Note: We are using *All Situations* as a trap game is more about the actual results on the ice than it is about a team's true underlying ability

In [2]:
# Warning: NHL Schedules not loading - https://github.com/davidjkrause/sportsipy/issues/14
# sportsipy_utils.pull_nhl_schedule('TOR', 2024)

In [3]:
# https://www.naturalstattrick.com/games.php?fromseason=20242025&thruseason=20242025&stype=2&sit=all&loc=B&team=All&rate=n
schedule_folder = f'{base_dir}data/natural_stat_trick'

df_games = []
for filename in tqdm(os.listdir(schedule_folder)):
    if 'games_' in filename:
        schedule_filepath = os.path.join(schedule_folder, filename)
        df_games_filepath = pl.scan_csv(schedule_filepath, null_values=["-"]).collect()
        if not df_games_filepath.is_empty():
            df_games += [df_games_filepath]
    
df_games = (pl.concat(df_games)
            .unique(subset=['Game', 'Team'], keep='first')
            .with_columns(
                pl.col('Game').str.split(" - ").list.get(0).str.strip_chars().str.strptime(pl.Datetime,'%Y-%m-%d').alias('Date')
            )
            .select(['Game', 'Team', 'Date', 'GF', 'GA', 'GF%', 'xGF', 'xGA', 'xGF%', 'SH%', 'SV%' ,'PDO'])
           )
utils.logger.info(f"Loaded {df_games.shape[0]/2} unique games from natural stattrick") 
df_games.head(5)

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 73.12it/s]
2025-09-13 16:45:20,957 [4006499702.py:19] [INFO] Loaded 21528.0 unique games from natural stattrick

shape: (5, 12)
┌─────────────────────────────────┬───────────────────┬─────────────────────┬─────┬───┬───────┬───────┬───────┬───────┐
│ Game                            ┆ Team              ┆ Date                ┆ GF  ┆ … ┆ xGF%  ┆ SH%   ┆ SV%   ┆ PDO   │
│ ---                             ┆ ---               ┆ ---                 ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                             ┆ str               ┆ datetime[μs]        ┆ i64 ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞═════════════════════════════════╪═══════════════════╪═════════════════════╪═════╪═══╪═══════╪═══════╪═══════╪═══════╡
│  2023-10-12 - Red Wings 3, Dev… ┆ Detroit Red Wings ┆ 2023-10-12 00:00:00 ┆ 3   ┆ … ┆ 41.24 ┆ 8.57  ┆ 85.19 ┆ 0.938 │
│  2020-03-01 - Kings 4, Golden … ┆ Los Angeles Kings ┆ 2020-03-01 00:00:00 ┆ 4   ┆ … ┆ 26.14 ┆ 23.53 ┆ 97.67 ┆ 1.212 │
│  2010-01-16 - Sabres 2, Island… ┆ Buffalo Sabres    ┆ 2010-01-16 00:00:00 ┆ 2   ┆ … ┆ 40.7  ┆ 6.06  ┆ 94.74 ┆ 1.008 │
│  2024-12-21 - Penguins 0, Devi… ┆ New Jersey Devils ┆ 2024-12-21 00:00:00 ┆ 3   ┆ … ┆ 67.47 ┆ 11.11 ┆ 100.0 ┆ 1.111 │
│  2018-02-18 - Stars 2, Sharks … ┆ Dallas Stars      ┆ 2018-02-18 00:00:00 ┆ 2   ┆ … ┆ 48.07 ┆ 7.14  ┆ 82.14 ┆ 0.893 │
└─────────────────────────────────┴───────────────────┴─────────────────────┴─────┴───┴───────┴───────┴───────┴───────┘

In [4]:
df_missing = df_games.filter(pl.col("GF%").is_null())
utils.logger.info(f"Found {df_missing.shape[0]} / {df_games.shape[0]} rows without any goals in all situations")

2025-09-13 16:45:20,974 [659697710.py:2] [INFO] Found 104 / 43056 rows without any goals in all situations

## Identify Trap Games

In [5]:
strength_col = "Points"
strong_threshold = 1.1
weak_threshold = 0.9

df_games_processed = (
    df_games.filter(pl.col("GF%").is_not_null())
      .unique(subset=['Game', 'Team'], keep='first')
      .sort("Game", descending=False)
      .with_columns([
        pl.when(pl.col("Date").dt.month() >= 7).then(pl.col("Date").dt.year() + 1)
            .otherwise(pl.col("Date").dt.year())
            .alias("Season"),
          pl.when(pl.col("GF%")>50).then(pl.lit(2))
              .when(pl.col("GF%")<50).then(pl.lit(0))
              .otherwise(pl.lit(1))
          .alias("Points")
      ])
    .with_columns([
        pl.col(strength_col).cum_sum().over(["Team", "Season"]).alias("Season to Date Total incl Current"),
        pl.col("GF%").cum_count().over(["Team", "Season"]).alias("# Games Season to Date incl Current")
    ])
    .with_columns(
        ((pl.col("Season to Date Total incl Current") - pl.col(strength_col))/
         (pl.col("# Games Season to Date incl Current") - 1)).alias(f"Season to Date Average {strength_col}")
    )
    .with_columns([
        ((pl.col(f"Season to Date Average {strength_col}") > strong_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_strong"),
        ((pl.col(f"Season to Date Average {strength_col}") < weak_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_weak"),

        pl.when(pl.col("Season") <= 2012).then(pl.lit("Pre-Lockout (2007–2012)"))
            .when(pl.col("Season") == 2013).then(pl.lit("2013 Lockout"))
            .when((pl.col("Season") >= 2014) & (pl.col("Season") <= 2019)).then(pl.lit("Post-Lockout (2014-2019)"))
            .when((pl.col("Season") >= 2020) & (pl.col("Season") <= 2021)).then(pl.lit("Pandemic (2020–2021)"))
            .otherwise(pl.lit("Post-Pandemic (2022–2025)"))
            .alias("Season Bucket")
    ])
)  
                     
display(df_games_processed.tail(5))
df_games_processed.mean()

shape: (5, 20)
┌───────────────────┬───────────────────────┬──────────────┬─────┬───┬────────────────┬───────────┬─────────┬───────────────┐
│ Game              ┆ Team                  ┆ Date         ┆ GF  ┆ … ┆ Season to Date ┆ is_strong ┆ is_weak ┆ Season Bucket │
│ ---               ┆ ---                   ┆ ---          ┆ --- ┆   ┆ Average Points ┆ ---       ┆ ---     ┆ ---           │
│ str               ┆ str                   ┆ datetime[μs] ┆ i64 ┆   ┆ ---            ┆ bool      ┆ bool    ┆ str           │
│                   ┆                       ┆              ┆     ┆   ┆ f64            ┆           ┆         ┆               │
╞═══════════════════╪═══════════════════════╪══════════════╪═════╪═══╪════════════════╪═══════════╪═════════╪═══════════════╡
│ 2025-04-17 -      ┆ Columbus Blue Jackets ┆ 2025-04-17   ┆ 6   ┆ … ┆ 0.9            ┆ false     ┆ false   ┆ Post-Pandemic │
│ Islanders 1, Blu… ┆                       ┆ 00:00:00     ┆     ┆   ┆                ┆           ┆         ┆ (2022–2025)   │
│ 2025-04-17 -      ┆ Tampa Bay Lightning   ┆ 2025-04-17   ┆ 0   ┆ … ┆ 1.17284        ┆ true      ┆ false   ┆ Post-Pandemic │
│ Lightning 0, Ran… ┆                       ┆ 00:00:00     ┆     ┆   ┆                ┆           ┆         ┆ (2022–2025)   │
│ 2025-04-17 -      ┆ New York Rangers      ┆ 2025-04-17   ┆ 4   ┆ … ┆ 0.925          ┆ false     ┆ false   ┆ Post-Pandemic │
│ Lightning 0, Ran… ┆                       ┆ 00:00:00     ┆     ┆   ┆                ┆           ┆         ┆ (2022–2025)   │
│ 2025-04-17 - Red  ┆ Detroit Red Wings     ┆ 2025-04-17   ┆ 3   ┆ … ┆ 0.925926       ┆ false     ┆ false   ┆ Post-Pandemic │
│ Wings 3, Map…     ┆                       ┆ 00:00:00     ┆     ┆   ┆                ┆           ┆         ┆ (2022–2025)   │
│ 2025-04-17 - Red  ┆ Toronto Maple Leafs   ┆ 2025-04-17   ┆ 4   ┆ … ┆ 1.271605       ┆ true      ┆ false   ┆ Post-Pandemic │
│ Wings 3, Map…     ┆                       ┆ 00:00:00     ┆     ┆   ┆                ┆           ┆         ┆ (2022–2025)   │
└───────────────────┴───────────────────────┴──────────────┴─────┴───┴────────────────┴───────────┴─────────┴───────────────┘

shape: (1, 20)
┌──────┬──────┬────────────────────────────┬──────────┬───┬───────────────────────────────┬───────────┬──────────┬───────────────┐
│ Game ┆ Team ┆ Date                       ┆ GF       ┆ … ┆ Season to Date Average Points ┆ is_strong ┆ is_weak  ┆ Season Bucket │
│ ---  ┆ ---  ┆ ---                        ┆ ---      ┆   ┆ ---                           ┆ ---       ┆ ---      ┆ ---           │
│ str  ┆ str  ┆ datetime[μs]               ┆ f64      ┆   ┆ f64                           ┆ f64       ┆ f64      ┆ str           │
╞══════╪══════╪════════════════════════════╪══════════╪═══╪═══════════════════════════════╪═══════════╪══════════╪═══════════════╡
│ null ┆ null ┆ 2016-08-21 05:52:29.413298 ┆ 2.860286 ┆ … ┆ NaN                           ┆ 0.232981  ┆ 0.225787 ┆ null          │
└──────┴──────┴────────────────────────────┴──────────┴───┴───────────────────────────────┴───────────┴──────────┴───────────────┘

In [6]:
# Double check season derivation is reasonable given lockout in the 2012-2013 season and pandemic in 2019-2020/2020-2021 seasons
df_games_processed.group_by("Season").agg(pl.col("Game").count()).sort("Game").head(5)

shape: (5, 2)
┌────────┬──────┐
│ Season ┆ Game │
│ ---    ┆ ---  │
│ i32    ┆ u32  │
╞════════╪══════╡
│ 2013   ┆ 1434 │
│ 2021   ┆ 1730 │
│ 2020   ┆ 2160 │
│ 2010   ┆ 2448 │
│ 2015   ┆ 2448 │
└────────┴──────┘

In [7]:
df_opponent = df_games_processed.select([
    pl.col("Game"),
    pl.col("Team").alias("Opponent"),
    pl.col(f"Season to Date Average {strength_col}").alias(f"Opponent Season to Date Average {strength_col}"),
    pl.col("is_strong").alias("Opponent is_strong"),
    pl.col("is_weak").alias("Opponent is_weak")
])

df_games_with_opponent = (
    df_games_processed.join(df_opponent, on="Game", how="left")
    .filter(pl.col("Team") != pl.col("Opponent"))
    .with_columns(
        (pl.col(f"Season to Date Average {strength_col}") - pl.col(f"Opponent Season to Date Average {strength_col}")).alias(f"Delta {strength_col}")
    )

    # Tag previous opponent
    .sort(["Team", "Date"])
    .with_columns([
        pl.col(col).shift(1).over(["Team", "Season"]).alias(f"Previous {col}")
        for col in ["Opponent", "Opponent is_strong", "Opponent is_weak", "GF%"]
    ])

    # Tag Trap Games: Strong Team that beat another strong team in the previous game faces a weak opponent in the next game
    .with_columns(
        pl.when((pl.col("is_strong"))&(pl.col("Opponent is_weak"))
                &(pl.col("Previous Opponent is_strong"))&(pl.col("Previous GF%") > 50))
            .then(pl.lit(True))
        .otherwise(pl.lit(False)).alias("Trap Game")
    )
)

assert df_games_with_opponent.shape[0] == df_games_processed.shape[0]

df_games_with_opponent.filter(pl.col("Trap Game"))

shape: (482, 30)
┌────────────────────┬───────────────┬──────────────┬─────┬───┬───────────────────┬───────────────────┬──────────────┬───────────┐
│ Game               ┆ Team          ┆ Date         ┆ GF  ┆ … ┆ Previous Opponent ┆ Previous Opponent ┆ Previous GF% ┆ Trap Game │
│ ---                ┆ ---           ┆ ---          ┆ --- ┆   ┆ is_strong         ┆ is_weak           ┆ ---          ┆ ---       │
│ str                ┆ str           ┆ datetime[μs] ┆ i64 ┆   ┆ ---               ┆ ---               ┆ f64          ┆ bool      │
│                    ┆               ┆              ┆     ┆   ┆ bool              ┆ bool              ┆              ┆           │
╞════════════════════╪═══════════════╪══════════════╪═════╪═══╪═══════════════════╪═══════════════════╪══════════════╪═══════════╡
│ 2013-03-31 - Ducks ┆ Anaheim Ducks ┆ 2013-03-31   ┆ 1   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ 1, Blue Ja…        ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-04-27 -       ┆ Anaheim Ducks ┆ 2013-04-27   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 75.0         ┆ true      │
│ Coyotes 5, Ducks…  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-12-09 -       ┆ Anaheim Ducks ┆ 2013-12-09   ┆ 5   ┆ … ┆ true              ┆ false             ┆ 71.43        ┆ true      │
│ Islanders 2, Duc…  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-12-15 -       ┆ Anaheim Ducks ┆ 2013-12-15   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ Oilers 2, Ducks …  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2014-01-03 -       ┆ Anaheim Ducks ┆ 2014-01-03   ┆ 5   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ Oilers 2, Ducks …  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ …                  ┆ …             ┆ …            ┆ …   ┆ … ┆ …                 ┆ …                 ┆ …            ┆ …         │
│ 2023-12-27 - Jets  ┆ Winnipeg Jets ┆ 2023-12-27   ┆ 1   ┆ … ┆ true              ┆ false             ┆ 83.33        ┆ true      │
│ 1, Blackhaw…       ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2024-04-16 -       ┆ Winnipeg Jets ┆ 2024-04-16   ┆ 4   ┆ … ┆ true              ┆ false             ┆ 100.0        ┆ true      │
│ Kraken 3, Jets 4   ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-03-16 - Jets  ┆ Winnipeg Jets ┆ 2025-03-16   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 80.0         ┆ true      │
│ 3, Kraken 2        ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-03-23 -       ┆ Winnipeg Jets ┆ 2025-03-23   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 57.14        ┆ true      │
│ Sabres 5, Jets 3   ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-04-12 - Jets  ┆ Winnipeg Jets ┆ 2025-04-12   ┆ 4   ┆ … ┆ true              ┆ false             ┆ 100.0        ┆ true      │
│ 5, Blackhaw…       ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
└────────────────────┴───────────────┴──────────────┴─────┴───┴───────────────────┴───────────────────┴──────────────┴───────────┘

In [8]:
df_leafs_sample = df_games_with_opponent.filter((pl.col("Team")=="Toronto Maple Leafs")&(pl.col("Season")==2025))
display(df_leafs_sample.head(5))

df_leafs_sample.write_csv(f"{base_dir}data/derived/Leafs Trap Games Sample.csv")

shape: (5, 30)
┌────────────────────────────┬───────────────┬──────────────┬─────┬───┬───────────┬───────────────────┬──────────────┬───────────┐
│ Game                       ┆ Team          ┆ Date         ┆ GF  ┆ … ┆ Previous  ┆ Previous Opponent ┆ Previous GF% ┆ Trap Game │
│ ---                        ┆ ---           ┆ ---          ┆ --- ┆   ┆ Opponent  ┆ is_weak           ┆ ---          ┆ ---       │
│ str                        ┆ str           ┆ datetime[μs] ┆ i64 ┆   ┆ is_strong ┆ ---               ┆ f64          ┆ bool      │
│                            ┆               ┆              ┆     ┆   ┆ ---       ┆ bool              ┆              ┆           │
│                            ┆               ┆              ┆     ┆   ┆ bool      ┆                   ┆              ┆           │
╞════════════════════════════╪═══════════════╪══════════════╪═════╪═══╪═══════════╪═══════════════════╪══════════════╪═══════════╡
│ 2024-10-09 - Maple Leafs   ┆ Toronto Maple ┆ 2024-10-09   ┆ 0   ┆ … ┆ null      ┆ null              ┆ null         ┆ false     │
│ 0, C…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-10 - Maple Leafs   ┆ Toronto Maple ┆ 2024-10-10   ┆ 4   ┆ … ┆ false     ┆ false             ┆ 0.0          ┆ false     │
│ 4, D…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-12 - Penguins 2,   ┆ Toronto Maple ┆ 2024-10-12   ┆ 4   ┆ … ┆ false     ┆ false             ┆ 66.67        ┆ false     │
│ Mapl…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-16 - Kings 2,      ┆ Toronto Maple ┆ 2024-10-16   ┆ 6   ┆ … ┆ false     ┆ false             ┆ 66.67        ┆ false     │
│ Maple L…                   ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-19 - Rangers 4,    ┆ Toronto Maple ┆ 2024-10-19   ┆ 1   ┆ … ┆ false     ┆ false             ┆ 75.0         ┆ false     │
│ Maple…                     ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
└────────────────────────────┴───────────────┴──────────────┴─────┴───┴───────────┴───────────────────┴──────────────┴───────────┘

## Aggregate Tables

In [9]:
def get_agg_tables(df: pl.DataFrame, groupby_cols: List[str]) -> [pl.DataFrame, pl.DataFrame]:
    """
    
    """
    df_agg = (
        df.filter((pl.col("is_strong"))&(pl.col("Opponent is_weak"))) # compare strong vs weak games
        .group_by(groupby_cols + ['Trap Game']) # depending on whether the strong team won against another strong team the previous game
        .agg([pl.col('Game').count().alias('Sample Size').cast(pl.Int32)] 
             + [pl.col(col).mean() for col in ['GF', 'GA', 'GF%', 'xGF', 'xGA', 'xGF%', 'SH%', 'SV%', 'PDO']])
        .sort(groupby_cols + ['Trap Game'])
    )

    # Calculate % change
    value_cols = [col for col in df_agg.columns if col not in groupby_cols and col != 'Trap Game']
    if len(groupby_cols) == 0:
        df_pct_change = df_agg.filter(pl.col('Trap Game')).select(value_cols) / df_agg.filter(~pl.col('Trap Game')).select(value_cols) - 1
    else:
        df_pct_change = (df_agg
            .pivot(index=groupby_cols, on='Trap Game', values=value_cols)
            .with_columns([(pl.col(f'{col}_true') / pl.col(f'{col}_false') - 1).alias(col) 
                           for col in value_cols])
            .drop([f'{col}_true' for col in value_cols] + [f'{col}_false' for col in value_cols])
        )
    
    return df_agg, df_pct_change

In [10]:
writer = pd.ExcelWriter(f'{base_dir}data/derived/Trap Games Pivot Tables.xlsx')

for groupby_cols in [[], ['Season Bucket'], ['Season'], ['Team'], ['Season Bucket', 'Team'], ['Season', 'Team']]:
    df_agg, df_pct_change = get_agg_tables(df_games_with_opponent, groupby_cols)

    utils.logger.info(f"Pivot tables by {groupby_cols}")
    display(df_agg)
    display(df_pct_change)

    df_agg.to_pandas().to_excel(writer, sheet_name=f"Agg {'_'.join(groupby_cols)}", index=False)
    df_pct_change.to_pandas().to_excel(writer, sheet_name=f"% Change {'_'.join(groupby_cols)}", index=False)

writer.close()

2025-09-13 16:45:21,381 [902400462.py:6] [INFO] Pivot tables by []

shape: (2, 11)
┌───────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Trap Game ┆ Sample Size ┆ GF       ┆ GA       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---       ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ bool      ┆ i32         ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ false     ┆ 2673        ┆ 3.27572  ┆ 2.575383 ┆ … ┆ 54.043471 ┆ 10.447995 ┆ 90.691938 ┆ 1.011404 │
│ true      ┆ 482         ┆ 3.475104 ┆ 2.522822 ┆ … ┆ 54.922676 ┆ 11.067282 ┆ 90.868071 ┆ 1.019342 │
└───────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (1, 10)
┌─────────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Sample Size ┆ GF       ┆ GA        ┆ GF%      ┆ … ┆ xGF%     ┆ SH%      ┆ SV%      ┆ PDO      │
│ ---         ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ -0.819678   ┆ 0.060867 ┆ -0.020409 ┆ 0.037863 ┆ … ┆ 0.016268 ┆ 0.059273 ┆ 0.001942 ┆ 0.007849 │
└─────────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

2025-09-13 16:45:21,402 [902400462.py:6] [INFO] Pivot tables by ['Season Bucket']

shape: (10, 12)
┌───────────────────────────┬───────────┬─────────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season Bucket             ┆ Trap Game ┆ Sample Size ┆ GF       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---                       ┆ ---       ┆ ---         ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str                       ┆ bool      ┆ i32         ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════════════════════╪═══════════╪═════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2013 Lockout              ┆ false     ┆ 81          ┆ 2.962963 ┆ … ┆ 52.320864 ┆ 9.939383  ┆ 90.882963 ┆ 1.008235 │
│ 2013 Lockout              ┆ true      ┆ 5           ┆ 2.4      ┆ … ┆ 51.286    ┆ 8.916     ┆ 91.254    ┆ 1.0016   │
│ Pandemic (2020–2021)      ┆ false     ┆ 314         ┆ 3.273885 ┆ … ┆ 54.281465 ┆ 10.48293  ┆ 91.242771 ┆ 1.017274 │
│ Pandemic (2020–2021)      ┆ true      ┆ 42          ┆ 3.142857 ┆ … ┆ 54.895238 ┆ 9.382619  ┆ 92.389524 ┆ 1.017643 │
│ Post-Lockout (2014-2019)  ┆ false     ┆ 921         ┆ 3.197611 ┆ … ┆ 53.632285 ┆ 10.154908 ┆ 91.003974 ┆ 1.011587 │
│ Post-Lockout (2014-2019)  ┆ true      ┆ 162         ┆ 3.407407 ┆ … ┆ 54.272222 ┆ 10.828519 ┆ 91.466358 ┆ 1.022926 │
│ Post-Pandemic (2022–2025) ┆ false     ┆ 754         ┆ 3.558355 ┆ … ┆ 55.489602 ┆ 11.237546 ┆ 90.232706 ┆ 1.01471  │
│ Post-Pandemic (2022–2025) ┆ true      ┆ 178         ┆ 3.853933 ┆ … ┆ 56.872865 ┆ 12.27264  ┆ 89.962135 ┆ 1.022371 │
│ Pre-Lockout (2007–2012)   ┆ false     ┆ 603         ┆ 3.084577 ┆ … ┆ 52.963967 ┆ 9.958507  ┆ 90.477081 ┆ 1.004358 │
│ Pre-Lockout (2007–2012)   ┆ true      ┆ 95          ┆ 3.084211 ┆ … ┆ 52.581368 ┆ 10.074    ┆ 90.852316 ┆ 1.009242 │
└───────────────────────────┴───────────┴─────────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5, 11)
┌───────────────────────────┬─────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season Bucket             ┆ Sample Size ┆ GF        ┆ GA        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---                       ┆ ---         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str                       ┆ f64         ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════════════════════╪═════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2013 Lockout              ┆ -0.938272   ┆ -0.19     ┆ -0.134951 ┆ … ┆ -0.019779 ┆ -0.102962 ┆ 0.004083  ┆ -0.00658 │
│ Pandemic (2020–2021)      ┆ -0.866242   ┆ -0.040022 ┆ -0.075211 ┆ … ┆ 0.011307  ┆ -0.104962 ┆ 0.012568  ┆ 0.000363 │
│ Post-Lockout (2014-2019)  ┆ -0.824104   ┆ 0.06561   ┆ -0.045588 ┆ … ┆ 0.011932  ┆ 0.066334  ┆ 0.005081  ┆ 0.011209 │
│ Post-Pandemic (2022–2025) ┆ -0.763926   ┆ 0.083066  ┆ -0.002928 ┆ … ┆ 0.024928  ┆ 0.09211   ┆ -0.002999 ┆ 0.00755  │
│ Pre-Lockout (2007–2012)   ┆ -0.842454   ┆ -0.000119 ┆ 0.001162  ┆ … ┆ -0.007224 ┆ 0.011597  ┆ 0.004147  ┆ 0.004863 │
└───────────────────────────┴─────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

2025-09-13 16:45:21,424 [902400462.py:6] [INFO] Pivot tables by ['Season']

shape: (36, 12)
┌────────┬───────────┬─────────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season ┆ Trap Game ┆ Sample Size ┆ GF       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---    ┆ ---       ┆ ---         ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32    ┆ bool      ┆ i32         ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞════════╪═══════════╪═════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2008   ┆ false     ┆ 79          ┆ 2.962025 ┆ … ┆ 51.641667 ┆ 9.945696  ┆ 89.458101 ┆ 0.994013 │
│ 2008   ┆ true      ┆ 11          ┆ 2.272727 ┆ … ┆ 48.54     ┆ 8.218182  ┆ 91.112727 ┆ 0.993273 │
│ 2009   ┆ false     ┆ 132         ┆ 3.280303 ┆ … ┆ 54.231615 ┆ 10.397955 ┆ 89.906439 ┆ 1.00303  │
│ 2009   ┆ true      ┆ 24          ┆ 3.583333 ┆ … ┆ 55.09     ┆ 10.694167 ┆ 92.03375  ┆ 1.027292 │
│ 2010   ┆ false     ┆ 153         ┆ 3.202614 ┆ … ┆ 52.853595 ┆ 10.25902  ┆ 90.693203 ┆ 1.009549 │
│ …      ┆ …         ┆ …           ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2023   ┆ true      ┆ 40          ┆ 4.175    ┆ … ┆ 56.479    ┆ 13.00225  ┆ 89.90125  ┆ 1.02905  │
│ 2024   ┆ false     ┆ 163         ┆ 3.723926 ┆ … ┆ 55.17227  ┆ 11.577975 ┆ 90.44681  ┆ 1.020282 │
│ 2024   ┆ true      ┆ 24          ┆ 3.333333 ┆ … ┆ 61.899167 ┆ 10.362083 ┆ 89.84125  ┆ 1.002125 │
│ 2025   ┆ false     ┆ 222         ┆ 3.189189 ┆ … ┆ 53.647838 ┆ 11.133333 ┆ 89.468108 ┆ 1.006032 │
│ 2025   ┆ true      ┆ 47          ┆ 3.382979 ┆ … ┆ 54.734043 ┆ 12.331915 ┆ 89.130426 ┆ 1.014638 │
└────────┴───────────┴─────────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (18, 11)
┌────────┬─────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Season ┆ Sample Size ┆ GF        ┆ GA        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---    ┆ ---         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i32    ┆ f64         ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════╪═════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2008   ┆ -0.860759   ┆ -0.232712 ┆ -0.020661 ┆ … ┆ -0.060061 ┆ -0.173695 ┆ 0.018496  ┆ -0.000744 │
│ 2009   ┆ -0.818182   ┆ 0.092379  ┆ -0.186828 ┆ … ┆ 0.015828  ┆ 0.028488  ┆ 0.023661  ┆ 0.024188  │
│ 2010   ┆ -0.836601   ┆ 0.011673  ┆ 0.192615  ┆ … ┆ -0.022507 ┆ -0.006182 ┆ -0.010184 ┆ -0.009855 │
│ 2011   ┆ -0.869919   ┆ -0.04986  ┆ -0.143113 ┆ … ┆ 0.011585  ┆ 0.105414  ┆ 0.00807   ┆ 0.017185  │
│ 2012   ┆ -0.836207   ┆ 0.002882  ┆ 0.140776  ┆ … ┆ -0.011239 ┆ 0.027859  ┆ -0.011792 ┆ -0.008041 │
│ …      ┆ …           ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2021   ┆ -0.896373   ┆ -0.153253 ┆ -0.039089 ┆ … ┆ -0.029715 ┆ -0.165567 ┆ 0.012444  ┆ -0.006501 │
│ 2022   ┆ -0.666667   ┆ 0.157025  ┆ 0.026616  ┆ … ┆ 0.016959  ┆ 0.15304   ┆ -0.001347 ┆ 0.015106  │
│ 2023   ┆ -0.761905   ┆ 0.092523  ┆ 0.087411  ┆ … ┆ -0.022642 ┆ 0.126671  ┆ -0.005731 ┆ 0.009303  │
│ 2024   ┆ -0.852761   ┆ -0.104887 ┆ -0.02512  ┆ … ┆ 0.121925  ┆ -0.105018 ┆ -0.006695 ┆ -0.017796 │
│ 2025   ┆ -0.788288   ┆ 0.060765  ┆ -0.099577 ┆ … ┆ 0.020247  ┆ 0.107657  ┆ -0.003774 ┆ 0.008555  │
└────────┴─────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

2025-09-13 16:45:21,451 [902400462.py:6] [INFO] Pivot tables by ['Team']

shape: (65, 12)
┌──────────────────────┬───────────┬─────────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Team                 ┆ Trap Game ┆ Sample Size ┆ GF       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---                  ┆ ---       ┆ ---         ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str                  ┆ bool      ┆ i32         ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════╪═════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Anaheim Ducks        ┆ false     ┆ 47          ┆ 3.170213 ┆ … ┆ 53.505745 ┆ 10.39766  ┆ 90.533404 ┆ 1.00934  │
│ Anaheim Ducks        ┆ true      ┆ 10          ┆ 2.5      ┆ … ┆ 54.578    ┆ 7.33      ┆ 89.976    ┆ 0.973    │
│ Atlanta Thrashers    ┆ false     ┆ 7           ┆ 3.285714 ┆ … ┆ 44.135714 ┆ 13.108571 ┆ 89.771429 ┆ 1.028857 │
│ Boston Bruins        ┆ false     ┆ 167         ┆ 3.281437 ┆ … ┆ 53.878144 ┆ 10.168743 ┆ 90.965808 ┆ 1.011353 │
│ Boston Bruins        ┆ true      ┆ 35          ┆ 3.342857 ┆ … ┆ 55.273429 ┆ 10.008286 ┆ 94.050571 ┆ 1.0406   │
│ …                    ┆ …         ┆ …           ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Vegas Golden Knights ┆ true      ┆ 18          ┆ 2.833333 ┆ … ┆ 51.740556 ┆ 10.036667 ┆ 89.192222 ┆ 0.992222 │
│ Washington Capitals  ┆ false     ┆ 165         ┆ 3.248485 ┆ … ┆ 52.225515 ┆ 10.612061 ┆ 89.957333 ┆ 1.005709 │
│ Washington Capitals  ┆ true      ┆ 30          ┆ 3.766667 ┆ … ┆ 51.794667 ┆ 12.459667 ┆ 92.197    ┆ 1.046533 │
│ Winnipeg Jets        ┆ false     ┆ 103         ┆ 3.019417 ┆ … ┆ 52.779806 ┆ 9.681165  ┆ 91.146796 ┆ 1.008282 │
│ Winnipeg Jets        ┆ true      ┆ 15          ┆ 3.866667 ┆ … ┆ 57.752    ┆ 12.328667 ┆ 88.284    ┆ 1.006067 │
└──────────────────────┴───────────┴─────────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (33, 11)
┌──────────────────────┬─────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Team                 ┆ Sample Size ┆ GF        ┆ GA        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---                  ┆ ---         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str                  ┆ f64         ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════════════════╪═════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Anaheim Ducks        ┆ -0.787234   ┆ -0.211409 ┆ -0.014516 ┆ … ┆ 0.02004   ┆ -0.295034 ┆ -0.006157 ┆ -0.036004 │
│ Atlanta Thrashers    ┆ null        ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Boston Bruins        ┆ -0.790419   ┆ 0.018717  ┆ -0.347305 ┆ … ┆ 0.025897  ┆ -0.015779 ┆ 0.033911  ┆ 0.028918  │
│ Buffalo Sabres       ┆ -0.92       ┆ 0.029412  ┆ 0.008065  ┆ … ┆ -0.172712 ┆ 0.129079  ┆ 0.014869  ┆ 0.027668  │
│ Calgary Flames       ┆ -0.796296   ┆ 0.029712  ┆ -0.217391 ┆ … ┆ 0.006682  ┆ -0.014185 ┆ 0.023569  ┆ 0.019165  │
│ …                    ┆ …           ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Toronto Maple Leafs  ┆ -0.785714   ┆ 0.031826  ┆ -0.11976  ┆ … ┆ 0.008986  ┆ 0.063838  ┆ 0.013034  ┆ 0.0186    │
│ Vancouver Canucks    ┆ -0.918367   ┆ -0.222222 ┆ -0.001073 ┆ … ┆ -0.011934 ┆ -0.255652 ┆ 0.006038  ┆ -0.021698 │
│ Vegas Golden Knights ┆ -0.772152   ┆ -0.21462  ┆ 0.145868  ┆ … ┆ -0.052637 ┆ -0.080678 ┆ -0.015965 ┆ -0.023014 │
│ Washington Capitals  ┆ -0.818182   ┆ 0.159515  ┆ -0.180851 ┆ … ┆ -0.00825  ┆ 0.174104  ┆ 0.024897  ┆ 0.040592  │
│ Winnipeg Jets        ┆ -0.854369   ┆ 0.2806    ┆ 0.170455  ┆ … ┆ 0.094206  ┆ 0.273469  ┆ -0.031409 ┆ -0.002197 │
└──────────────────────┴─────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

2025-09-13 16:45:21,481 [902400462.py:6] [INFO] Pivot tables by ['Season Bucket', 'Team']

shape: (200, 13)
┌─────────────────────────┬─────────────────────┬───────────┬─────────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season Bucket           ┆ Team                ┆ Trap Game ┆ Sample Size ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---                     ┆ ---                 ┆ ---       ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str                     ┆ str                 ┆ bool      ┆ i32         ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═════════════════════════╪═════════════════════╪═══════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2013 Lockout            ┆ Anaheim Ducks       ┆ false     ┆ 9           ┆ … ┆ 49.795556 ┆ 7.343333  ┆ 91.301111 ┆ 0.986556 │
│ 2013 Lockout            ┆ Anaheim Ducks       ┆ true      ┆ 2           ┆ … ┆ 56.34     ┆ 4.925     ┆ 86.38     ┆ 0.913    │
│ 2013 Lockout            ┆ Boston Bruins       ┆ false     ┆ 10          ┆ … ┆ 52.148    ┆ 10.421    ┆ 94.417    ┆ 1.0484   │
│ 2013 Lockout            ┆ Carolina Hurricanes ┆ false     ┆ 5           ┆ … ┆ 50.034    ┆ 7.63      ┆ 91.206    ┆ 0.9886   │
│ 2013 Lockout            ┆ Chicago Blackhawks  ┆ false     ┆ 14          ┆ … ┆ 56.194286 ┆ 8.965714  ┆ 90.451429 ┆ 0.994214 │
│ …                       ┆ …                   ┆ …         ┆ …           ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Pre-Lockout (2007–2012) ┆ Tampa Bay Lightning ┆ true      ┆ 1           ┆ … ┆ 55.58     ┆ 6.25      ┆ 80.0      ┆ 0.863    │
│ Pre-Lockout (2007–2012) ┆ Vancouver Canucks   ┆ false     ┆ 50          ┆ … ┆ 53.62898  ┆ 9.5616    ┆ 91.7864   ┆ 1.01348  │
│ Pre-Lockout (2007–2012) ┆ Vancouver Canucks   ┆ true      ┆ 7           ┆ … ┆ 52.251429 ┆ 8.867143  ┆ 91.444286 ┆ 1.003143 │
│ Pre-Lockout (2007–2012) ┆ Washington Capitals ┆ false     ┆ 57          ┆ … ┆ 53.265789 ┆ 10.232632 ┆ 90.821579 ┆ 1.010544 │
│ Pre-Lockout (2007–2012) ┆ Washington Capitals ┆ true      ┆ 9           ┆ … ┆ 52.687778 ┆ 12.737778 ┆ 90.265556 ┆ 1.03     │
└─────────────────────────┴─────────────────────┴───────────┴─────────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (114, 12)
┌─────────────────────────┬─────────────────────┬─────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Season Bucket           ┆ Team                ┆ Sample Size ┆ GF        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---                     ┆ ---                 ┆ ---         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str                     ┆ str                 ┆ f64         ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═════════════════════════╪═════════════════════╪═════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2013 Lockout            ┆ Anaheim Ducks       ┆ -0.777778   ┆ -0.052632 ┆ … ┆ 0.131426  ┆ -0.329324 ┆ -0.0539   ┆ -0.074558 │
│ 2013 Lockout            ┆ Boston Bruins       ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2013 Lockout            ┆ Carolina Hurricanes ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2013 Lockout            ┆ Chicago Blackhawks  ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2013 Lockout            ┆ Los Angeles Kings   ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …                       ┆ …                   ┆ …           ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Pre-Lockout (2007–2012) ┆ San Jose Sharks     ┆ -0.888889   ┆ 0.413223  ┆ … ┆ -0.035402 ┆ 0.404548  ┆ 0.016122  ┆ 0.048613  │
│ Pre-Lockout (2007–2012) ┆ St Louis Blues      ┆ -0.909091   ┆ -0.098361 ┆ … ┆ -0.348189 ┆ 0.14714   ┆ -0.006601 ┆ 0.007438  │
│ Pre-Lockout (2007–2012) ┆ Tampa Bay Lightning ┆ -0.9375     ┆ -0.157895 ┆ … ┆ -0.007865 ┆ -0.147194 ┆ -0.104544 ┆ -0.107434 │
│ Pre-Lockout (2007–2012) ┆ Vancouver Canucks   ┆ -0.86       ┆ -0.112979 ┆ … ┆ -0.025687 ┆ -0.07263  ┆ -0.003727 ┆ -0.0102   │
│ Pre-Lockout (2007–2012) ┆ Washington Capitals ┆ -0.842105   ┆ 0.31383   ┆ … ┆ -0.010851 ┆ 0.244819  ┆ -0.006122 ┆ 0.019253  │
└─────────────────────────┴─────────────────────┴─────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

2025-09-13 16:45:21,535 [902400462.py:6] [INFO] Pivot tables by ['Season', 'Team']

shape: (470, 13)
┌────────┬──────────────────────┬───────────┬─────────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season ┆ Team                 ┆ Trap Game ┆ Sample Size ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---    ┆ ---                  ┆ ---       ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32    ┆ str                  ┆ bool      ┆ i32         ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞════════╪══════════════════════╪═══════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2008   ┆ Anaheim Ducks        ┆ false     ┆ 3           ┆ … ┆ 45.696667 ┆ 11.01     ┆ 94.066667 ┆ 1.051    │
│ 2008   ┆ Boston Bruins        ┆ false     ┆ 2           ┆ … ┆ 47.52     ┆ 9.3       ┆ 87.085    ┆ 0.964    │
│ 2008   ┆ Carolina Hurricanes  ┆ false     ┆ 2           ┆ … ┆ 48.28     ┆ 5.735     ┆ 90.86     ┆ 0.966    │
│ 2008   ┆ Carolina Hurricanes  ┆ true      ┆ 1           ┆ … ┆ 62.29     ┆ 4.17      ┆ 93.75     ┆ 0.979    │
│ 2008   ┆ Dallas Stars         ┆ false     ┆ 1           ┆ … ┆ 66.82     ┆ 12.82     ┆ 90.91     ┆ 1.037    │
│ …      ┆ …                    ┆ …         ┆ …           ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025   ┆ Vegas Golden Knights ┆ true      ┆ 4           ┆ … ┆ 49.5425   ┆ 12.795    ┆ 85.635    ┆ 0.98425  │
│ 2025   ┆ Washington Capitals  ┆ false     ┆ 23          ┆ … ┆ 53.083478 ┆ 12.126957 ┆ 88.042174 ┆ 1.001696 │
│ 2025   ┆ Washington Capitals  ┆ true      ┆ 6           ┆ … ┆ 51.02     ┆ 12.158333 ┆ 90.016667 ┆ 1.021833 │
│ 2025   ┆ Winnipeg Jets        ┆ false     ┆ 21          ┆ … ┆ 52.612857 ┆ 8.634286  ┆ 90.90381  ┆ 0.995333 │
│ 2025   ┆ Winnipeg Jets        ┆ true      ┆ 3           ┆ … ┆ 59.603333 ┆ 9.796667  ┆ 82.856667 ┆ 0.926333 │
└────────┴──────────────────────┴───────────┴─────────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (281, 12)
┌────────┬──────────────────────┬─────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Season ┆ Team                 ┆ Sample Size ┆ GF        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---    ┆ ---                  ┆ ---         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i32    ┆ str                  ┆ f64         ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════╪══════════════════════╪═════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2008   ┆ Anaheim Ducks        ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2008   ┆ Boston Bruins        ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2008   ┆ Carolina Hurricanes  ┆ -0.5        ┆ -0.5      ┆ … ┆ 0.290182  ┆ -0.272886 ┆ 0.031807  ┆ 0.013458  │
│ 2008   ┆ Dallas Stars         ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2008   ┆ Detroit Red Wings    ┆ -0.818182   ┆ -0.108108 ┆ … ┆ -0.247294 ┆ 0.196137  ┆ 0.017472  ┆ 0.033784  │
│ …      ┆ …                    ┆ …           ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025   ┆ Toronto Maple Leafs  ┆ -0.555556   ┆ 0.182203  ┆ … ┆ 0.201215  ┆ 0.213228  ┆ 0.030017  ┆ 0.050832  │
│ 2025   ┆ Vancouver Canucks    ┆ null        ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025   ┆ Vegas Golden Knights ┆ -0.809524   ┆ -0.148649 ┆ … ┆ -0.112747 ┆ 0.140471  ┆ -0.041021 ┆ -0.020925 │
│ 2025   ┆ Washington Capitals  ┆ -0.73913    ┆ -0.054113 ┆ … ┆ -0.038872 ┆ 0.002587  ┆ 0.022427  ┆ 0.020104  │
│ 2025   ┆ Winnipeg Jets        ┆ -0.857143   ┆ 0.346154  ┆ … ┆ 0.132866  ┆ 0.134624  ┆ -0.088524 ┆ -0.069324 │
└────────┴──────────────────────┴─────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Permutation Tests

- Test Statistic: Difference in $GF\%$ between trap games and similar non-trap games  
- $H_0$: No difference between trap games and similar non-trap games. Any difference due to random chance alone
- $H_1$: Teams perform worse in trap games, i.e., Test Statistic < 0

In [11]:
def get_pvalues(df: pl.DataFrame, groupby_cols: List[str], num_simulations: int=1000) -> pl.DataFrame:
    """
    Run a one-sided permutation test on alternative hypothesis that teams perform worse in trap games on a GF% basis
    :param df: pl.DataFrame
    :param groupby_cols: List[str]
    :param num_simulations: int
    :return: pl.DataFrame
    """
    # Observed Test Stat
    _, df_pct_change_obs = get_agg_tables(df, groupby_cols)
    df_obs = df_pct_change_obs.select(groupby_cols + ['GF%']).rename({'GF%': 'Observed GF%'})
    
    # Derive Simulated Test Stats
    sim_results = []
    for i in tqdm(range(num_simulations)):
        df_permuted_all = []
        for category, df_group in df.group_by(groupby_cols, maintain_order=True):
            # Permute 'GF%' labels among all similar games
            df_permuted = df_group.filter((pl.col("is_strong"))&(pl.col("Opponent is_weak"))) # compare strong vs weak games
            permuted_values = np.random.permutation(df_permuted['GF%'].to_numpy())
            df_permuted = df_permuted.with_columns(pl.Series('GF%', permuted_values))
            df_permuted_all.append(df_permuted)
        
        df_permuted_all = pl.concat(df_permuted_all)
        _, df_pct_change_perm = get_agg_tables(df_permuted_all, groupby_cols)
        
        sim_results.append(
            df_pct_change_perm.select(groupby_cols + ['GF%'])
            .rename({'GF%': 'Simulated GF%'})
            .with_columns(pl.lit(i).alias("Simulation"))
        )
    
    # one row per groupby_col x simulation # x simulated test stat
    df_simulated = pl.concat(sim_results)
    df_test_stats = df_simulated.join(df_obs, on=groupby_cols, how="left")
    
    # One-sided p-value where observed test stats are further in the direction of the alternative
    df_pvals = (
        df_test_stats
        .with_columns(
            (pl.col("Simulated GF%") <= pl.col("Observed GF%")).cast(pl.Int32).alias("Extreme")
        )
        .group_by(groupby_cols)
        .agg([
            pl.mean("Extreme").alias("P-Value"),
            pl.first("Observed GF%"),   # keep observed stat
        ])
    ).filter(pl.col('P-Value').is_not_null()).sort('P-Value')

    return df_pvals

In [ ]:
writer = pd.ExcelWriter(f'{base_dir}data/derived/Trap Games P-Values.xlsx')

for groupby_cols in [['Season'], ['Team'], ['Season Bucket', 'Team']]:
    utils.logger.info(groupby_cols)
    df_pvals = get_pvalues(df_games_with_opponent, groupby_cols, 10000)
    display(df_pvals)

    df_pvals.to_pandas().to_excel(writer, sheet_name=f"P-Value {'_'.join(groupby_cols)}", index=False)

writer.close()

2025-09-13 16:45:21,849 [643730260.py:4] [INFO] ['Season']
  1%|▌                                                                                        | 60/10000 [00:01<03:00, 55.22it/s]