# NHL Trap Games

Definition: A trap game is about a good team underperforming when they're expected to win

In [1]:
import sys
import os
import polars as pl
from tqdm import tqdm

base_dir = '../'
sys.path.insert(1, base_dir)

import src.config as cfg
import src.utils as utils
import src.sportsipy_utils as sportsipy_utils

## Pull Schedule for Each NHL Team

Note: We are using *All Situations* as a trap game is more about the actual results on the ice than it is about a team's true underlying ability

In [2]:
# Warning: NHL Schedules not loading - https://github.com/davidjkrause/sportsipy/issues/14
# sportsipy_utils.pull_nhl_schedule('TOR', 2024)

In [3]:
# https://www.naturalstattrick.com/games.php?fromseason=20242025&thruseason=20242025&stype=2&sit=all&loc=B&team=All&rate=n
schedule_folder = f'{base_dir}data/natural_stat_trick'

df_games = []
for filename in tqdm(os.listdir(schedule_folder)):
    if 'games_' in filename:
        schedule_filepath = os.path.join(schedule_folder, filename)
        df_games_filepath = pl.scan_csv(schedule_filepath, null_values=["-"]).collect()
        if not df_games_filepath.is_empty():
            df_games += [df_games_filepath]
    
df_games = (pl.concat(df_games)
            .unique(subset=['Game', 'Team'], keep='first')
            .with_columns(
                pl.col('Game').str.split(" - ").list.get(0).str.strip_chars().str.strptime(pl.Datetime,'%Y-%m-%d').alias('Date')
            )
            .select(['Game', 'Team', 'Date', 'GF', 'GA', 'GF%', 'xGF', 'xGA', 'xGF%', 'SH%', 'SV%' ,'PDO'])
           )
utils.logger.info(f"Loaded {df_games.shape[0]/2} unique games from natural stattrick") 
df_games.head(5)

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 84.58it/s]
2025-09-13 15:10:20,567 [1402038357.py:19] [INFO] Loaded 21528.0 unique games from natural stattrick

shape: (5, 12)
┌─────────────────────────────────┬─────────────────────┬─────────────────────┬─────┬───┬───────┬──────┬───────┬───────┐
│ Game                            ┆ Team                ┆ Date                ┆ GF  ┆ … ┆ xGF%  ┆ SH%  ┆ SV%   ┆ PDO   │
│ ---                             ┆ ---                 ┆ ---                 ┆ --- ┆   ┆ ---   ┆ ---  ┆ ---   ┆ ---   │
│ str                             ┆ str                 ┆ datetime[μs]        ┆ i64 ┆   ┆ f64   ┆ f64  ┆ f64   ┆ f64   │
╞═════════════════════════════════╪═════════════════════╪═════════════════════╪═════╪═══╪═══════╪══════╪═══════╪═══════╡
│  2019-10-30 - Panthers 4, Aval… ┆ Colorado Avalanche  ┆ 2019-10-30 00:00:00 ┆ 3   ┆ … ┆ 49.75 ┆ 10.0 ┆ 89.47 ┆ 0.995 │
│  2023-01-19 - Panthers 6, Cana… ┆ Montreal Canadiens  ┆ 2023-01-19 00:00:00 ┆ 2   ┆ … ┆ 30.48 ┆ 8.0  ┆ 85.0  ┆ 0.93  │
│  2019-12-09 - Islanders 5, Lig… ┆ Tampa Bay Lightning ┆ 2019-12-09 00:00:00 ┆ 1   ┆ … ┆ 56.97 ┆ 3.13 ┆ 79.17 ┆ 0.823 │
│  2007-12-13 - Avalanche 2, Pre… ┆ Colorado Avalanche  ┆ 2007-12-13 00:00:00 ┆ 2   ┆ … ┆ 50.92 ┆ 6.25 ┆ 96.77 ┆ 1.03  │
│  2010-01-30 - Blackhawks 2, Hu… ┆ Chicago Blackhawks  ┆ 2010-01-30 00:00:00 ┆ 2   ┆ … ┆ 61.24 ┆ 4.88 ┆ 83.33 ┆ 0.882 │
└─────────────────────────────────┴─────────────────────┴─────────────────────┴─────┴───┴───────┴──────┴───────┴───────┘

In [5]:
df_missing = df_games.filter(pl.col("GF%").is_null())
utils.logger.info(f"Found {df_missing.shape[0]} / {df_games.shape[0]} rows without any goals in all situations")

2025-09-13 15:10:43,805 [659697710.py:2] [INFO] Found 104 / 43056 rows without any goals in all situations

## Identify Trap Games

In [6]:
strength_col = "Points"
strong_threshold = 1.1
weak_threshold = 0.9

df_games_processed = (
    df_games.filter(pl.col("GF%").is_not_null())
      .unique(subset=['Game', 'Team'], keep='first')
      .sort("Game", descending=False)
      .with_columns([
        pl.when(pl.col("Date").dt.month() >= 7).then(pl.col("Date").dt.year() + 1)
            .otherwise(pl.col("Date").dt.year())
            .alias("Season"),
          pl.when(pl.col("GF%")>50).then(pl.lit(2))
              .when(pl.col("GF%")<50).then(pl.lit(0))
              .otherwise(pl.lit(1))
          .alias("Points")
      ])
    .with_columns([
        pl.col(strength_col).cum_sum().over(["Team", "Season"]).alias("Season to Date Total incl Current"),
        pl.col("GF%").cum_count().over(["Team", "Season"]).alias("# Games Season to Date incl Current")
    ])
    .with_columns(
        ((pl.col("Season to Date Total incl Current") - pl.col(strength_col))/
         (pl.col("# Games Season to Date incl Current") - 1)).alias(f"Season to Date Average {strength_col}")
    )
    .with_columns([
        ((pl.col(f"Season to Date Average {strength_col}") > strong_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_strong"),
        ((pl.col(f"Season to Date Average {strength_col}") < weak_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_weak")
    ])
)  
                     
display(df_games_processed.tail(5))
df_games_processed.mean()

shape: (5, 19)
┌─────────────────────┬─────────────────────┬──────────────┬─────┬───┬────────────────────┬────────────────┬───────────┬─────────┐
│ Game                ┆ Team                ┆ Date         ┆ GF  ┆ … ┆ # Games Season to  ┆ Season to Date ┆ is_strong ┆ is_weak │
│ ---                 ┆ ---                 ┆ ---          ┆ --- ┆   ┆ Date incl Cu…      ┆ Average Points ┆ ---       ┆ ---     │
│ str                 ┆ str                 ┆ datetime[μs] ┆ i64 ┆   ┆ ---                ┆ ---            ┆ bool      ┆ bool    │
│                     ┆                     ┆              ┆     ┆   ┆ u32                ┆ f64            ┆           ┆         │
╞═════════════════════╪═════════════════════╪══════════════╪═════╪═══╪════════════════════╪════════════════╪═══════════╪═════════╡
│ 2025-04-17 -        ┆ New York Islanders  ┆ 2025-04-17   ┆ 1   ┆ … ┆ 82                 ┆ 0.876543       ┆ false     ┆ true    │
│ Islanders 1, Blu…   ┆                     ┆ 00:00:00     ┆     ┆   ┆                    ┆                ┆           ┆         │
│ 2025-04-17 -        ┆ New York Rangers    ┆ 2025-04-17   ┆ 4   ┆ … ┆ 81                 ┆ 0.925          ┆ false     ┆ false   │
│ Lightning 0, Ran…   ┆                     ┆ 00:00:00     ┆     ┆   ┆                    ┆                ┆           ┆         │
│ 2025-04-17 -        ┆ Tampa Bay Lightning ┆ 2025-04-17   ┆ 0   ┆ … ┆ 82                 ┆ 1.17284        ┆ true      ┆ false   │
│ Lightning 0, Ran…   ┆                     ┆ 00:00:00     ┆     ┆   ┆                    ┆                ┆           ┆         │
│ 2025-04-17 - Red    ┆ Detroit Red Wings   ┆ 2025-04-17   ┆ 3   ┆ … ┆ 82                 ┆ 0.925926       ┆ false     ┆ false   │
│ Wings 3, Map…       ┆                     ┆ 00:00:00     ┆     ┆   ┆                    ┆                ┆           ┆         │
│ 2025-04-17 - Red    ┆ Toronto Maple Leafs ┆ 2025-04-17   ┆ 4   ┆ … ┆ 82                 ┆ 1.271605       ┆ true      ┆ false   │
│ Wings 3, Map…       ┆                     ┆ 00:00:00     ┆     ┆   ┆                    ┆                ┆           ┆         │
└─────────────────────┴─────────────────────┴──────────────┴─────┴───┴────────────────────┴────────────────┴───────────┴─────────┘

shape: (1, 19)
┌──────┬──────┬─────────────────┬──────────┬───┬────────────────────────┬─────────────────────────────────┬───────────┬──────────┐
│ Game ┆ Team ┆ Date            ┆ GF       ┆ … ┆ # Games Season to Date ┆ Season to Date Average Points   ┆ is_strong ┆ is_weak  │
│ ---  ┆ ---  ┆ ---             ┆ ---      ┆   ┆ incl Cu…               ┆ ---                             ┆ ---       ┆ ---      │
│ str  ┆ str  ┆ datetime[μs]    ┆ f64      ┆   ┆ ---                    ┆ f64                             ┆ f64       ┆ f64      │
│      ┆      ┆                 ┆          ┆   ┆ f64                    ┆                                 ┆           ┆          │
╞══════╪══════╪═════════════════╪══════════╪═══╪════════════════════════╪═════════════════════════════════╪═══════════╪══════════╡
│ null ┆ null ┆ 2016-08-21      ┆ 2.860286 ┆ … ┆ 40.005751              ┆ NaN                             ┆ 0.232981  ┆ 0.225787 │
│      ┆      ┆ 05:52:29.413298 ┆          ┆   ┆                        ┆                                 ┆           ┆          │
└──────┴──────┴─────────────────┴──────────┴───┴────────────────────────┴─────────────────────────────────┴───────────┴──────────┘

In [7]:
# Double check season derivation is reasonable given lockout in the 2012-2013 season and pandemic in 2019-2020/2020-2021 seasons
df_games_processed.group_by("Season").agg(pl.col("Game").count()).sort("Game").head(5)

shape: (5, 2)
┌────────┬──────┐
│ Season ┆ Game │
│ ---    ┆ ---  │
│ i32    ┆ u32  │
╞════════╪══════╡
│ 2013   ┆ 1434 │
│ 2021   ┆ 1730 │
│ 2020   ┆ 2160 │
│ 2010   ┆ 2448 │
│ 2015   ┆ 2448 │
└────────┴──────┘

In [8]:
df_opponent = df_games_processed.select([
    pl.col("Game"),
    pl.col("Team").alias("Opponent"),
    pl.col(f"Season to Date Average {strength_col}").alias(f"Opponent Season to Date Average {strength_col}"),
    pl.col("is_strong").alias("Opponent is_strong"),
    pl.col("is_weak").alias("Opponent is_weak")
])

df_games_with_opponent = (
    df_games_processed.join(df_opponent, on="Game", how="left")
    .filter(pl.col("Team") != pl.col("Opponent"))
    .with_columns(
        (pl.col(f"Season to Date Average {strength_col}") - pl.col(f"Opponent Season to Date Average {strength_col}")).alias(f"Delta {strength_col}")
    )

    # Tag previous opponent
    .sort(["Team", "Date"])
    .with_columns([
        pl.col(col).shift(1).over(["Team", "Season"]).alias(f"Previous {col}")
        for col in ["Opponent", "Opponent is_strong", "Opponent is_weak", "GF%"]
    ])

    # Tag Trap Games: Strong Team that beat another strong team in the previous game faces a weak opponent in the next game
    .with_columns(
        pl.when((pl.col("is_strong"))&(pl.col("Opponent is_weak"))
                &(pl.col("Previous Opponent is_strong"))&(pl.col("Previous GF%") > 50))
            .then(pl.lit(True))
        .otherwise(pl.lit(False)).alias("Trap Game")
    )
)

assert df_games_with_opponent.shape[0] == df_games_processed.shape[0]

df_games_with_opponent.filter(pl.col("Trap Game"))

shape: (482, 29)
┌────────────────────┬───────────────┬──────────────┬─────┬───┬───────────────────┬───────────────────┬──────────────┬───────────┐
│ Game               ┆ Team          ┆ Date         ┆ GF  ┆ … ┆ Previous Opponent ┆ Previous Opponent ┆ Previous GF% ┆ Trap Game │
│ ---                ┆ ---           ┆ ---          ┆ --- ┆   ┆ is_strong         ┆ is_weak           ┆ ---          ┆ ---       │
│ str                ┆ str           ┆ datetime[μs] ┆ i64 ┆   ┆ ---               ┆ ---               ┆ f64          ┆ bool      │
│                    ┆               ┆              ┆     ┆   ┆ bool              ┆ bool              ┆              ┆           │
╞════════════════════╪═══════════════╪══════════════╪═════╪═══╪═══════════════════╪═══════════════════╪══════════════╪═══════════╡
│ 2013-03-31 - Ducks ┆ Anaheim Ducks ┆ 2013-03-31   ┆ 1   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ 1, Blue Ja…        ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-04-27 -       ┆ Anaheim Ducks ┆ 2013-04-27   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 75.0         ┆ true      │
│ Coyotes 5, Ducks…  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-12-09 -       ┆ Anaheim Ducks ┆ 2013-12-09   ┆ 5   ┆ … ┆ true              ┆ false             ┆ 71.43        ┆ true      │
│ Islanders 2, Duc…  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2013-12-15 -       ┆ Anaheim Ducks ┆ 2013-12-15   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ Oilers 2, Ducks …  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2014-01-03 -       ┆ Anaheim Ducks ┆ 2014-01-03   ┆ 5   ┆ … ┆ true              ┆ false             ┆ 66.67        ┆ true      │
│ Oilers 2, Ducks …  ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ …                  ┆ …             ┆ …            ┆ …   ┆ … ┆ …                 ┆ …                 ┆ …            ┆ …         │
│ 2023-12-27 - Jets  ┆ Winnipeg Jets ┆ 2023-12-27   ┆ 1   ┆ … ┆ true              ┆ false             ┆ 83.33        ┆ true      │
│ 1, Blackhaw…       ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2024-04-16 -       ┆ Winnipeg Jets ┆ 2024-04-16   ┆ 4   ┆ … ┆ true              ┆ false             ┆ 100.0        ┆ true      │
│ Kraken 3, Jets 4   ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-03-16 - Jets  ┆ Winnipeg Jets ┆ 2025-03-16   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 80.0         ┆ true      │
│ 3, Kraken 2        ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-03-23 -       ┆ Winnipeg Jets ┆ 2025-03-23   ┆ 3   ┆ … ┆ true              ┆ false             ┆ 57.14        ┆ true      │
│ Sabres 5, Jets 3   ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
│ 2025-04-12 - Jets  ┆ Winnipeg Jets ┆ 2025-04-12   ┆ 4   ┆ … ┆ true              ┆ false             ┆ 100.0        ┆ true      │
│ 5, Blackhaw…       ┆               ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆              ┆           │
└────────────────────┴───────────────┴──────────────┴─────┴───┴───────────────────┴───────────────────┴──────────────┴───────────┘

In [9]:
df_leafs_sample = df_games_with_opponent.filter((pl.col("Team")=="Toronto Maple Leafs")&(pl.col("Season")==2025))
display(df_leafs_sample.head(5))

df_leafs_sample.write_csv(f"{base_dir}data/derived/Leafs Trap Games Sample.csv")

shape: (5, 29)
┌────────────────────────────┬───────────────┬──────────────┬─────┬───┬───────────┬───────────────────┬──────────────┬───────────┐
│ Game                       ┆ Team          ┆ Date         ┆ GF  ┆ … ┆ Previous  ┆ Previous Opponent ┆ Previous GF% ┆ Trap Game │
│ ---                        ┆ ---           ┆ ---          ┆ --- ┆   ┆ Opponent  ┆ is_weak           ┆ ---          ┆ ---       │
│ str                        ┆ str           ┆ datetime[μs] ┆ i64 ┆   ┆ is_strong ┆ ---               ┆ f64          ┆ bool      │
│                            ┆               ┆              ┆     ┆   ┆ ---       ┆ bool              ┆              ┆           │
│                            ┆               ┆              ┆     ┆   ┆ bool      ┆                   ┆              ┆           │
╞════════════════════════════╪═══════════════╪══════════════╪═════╪═══╪═══════════╪═══════════════════╪══════════════╪═══════════╡
│ 2024-10-09 - Maple Leafs   ┆ Toronto Maple ┆ 2024-10-09   ┆ 0   ┆ … ┆ null      ┆ null              ┆ null         ┆ false     │
│ 0, C…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-10 - Maple Leafs   ┆ Toronto Maple ┆ 2024-10-10   ┆ 4   ┆ … ┆ false     ┆ false             ┆ 0.0          ┆ false     │
│ 4, D…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-12 - Penguins 2,   ┆ Toronto Maple ┆ 2024-10-12   ┆ 4   ┆ … ┆ false     ┆ false             ┆ 66.67        ┆ false     │
│ Mapl…                      ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-16 - Kings 2,      ┆ Toronto Maple ┆ 2024-10-16   ┆ 6   ┆ … ┆ false     ┆ false             ┆ 66.67        ┆ false     │
│ Maple L…                   ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
│ 2024-10-19 - Rangers 4,    ┆ Toronto Maple ┆ 2024-10-19   ┆ 1   ┆ … ┆ false     ┆ false             ┆ 75.0         ┆ false     │
│ Maple…                     ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆           ┆                   ┆              ┆           │
└────────────────────────────┴───────────────┴──────────────┴─────┴───┴───────────┴───────────────────┴──────────────┴───────────┘

## Aggregate Tables

In [22]:
from typing import List

In [92]:
def get_agg_tables(df: pl.DataFrame, groupby_cols: List[str]) -> [pl.DataFrame, pl.DataFrame]:
    df_agg = (
        df.filter((pl.col("is_strong"))&(pl.col("Opponent is_weak"))) # compare strong vs weak games
        .group_by(groupby_cols + ['Trap Game']) # depending on whether the strong team won against another strong team the previous game
        .agg([pl.col('Game').count().alias('Sample Size').cast(pl.Int32)] 
             + [pl.col(col).mean() for col in ['GF', 'GA', 'GF%', 'xGF', 'xGA', 'xGF%', 'SH%', 'SV%', 'PDO']])
        .sort(groupby_cols + ['Trap Game'])
    )

    # Calculate % change
    value_cols = [col for col in df_agg.columns if col not in groupby_cols and col != 'Trap Game']
    if len(groupby_cols) == 0:
        df_pct_change = df_agg.filter(pl.col('Trap Game')).select(value_cols) / df_agg.filter(~pl.col('Trap Game')).select(value_cols) - 1
    else:
        df_pct_change = (df_agg
            .pivot(index=groupby_cols, on='Trap Game', values=value_cols)
            .with_columns([(pl.col(f'{col}_true') / pl.col(f'{col}_false') - 1).alias(col) 
                           for col in value_cols])
            .drop([f'{col}_true' for col in value_cols] + [f'{col}_false' for col in value_cols])
        )
    
    return df_agg, df_pct_change

In [98]:
for groupby_cols in [[], ['Season'], ['Team']]:
    df_agg, df_pct_change = get_agg_tables(df_games_with_opponent, groupby_cols)

    utils.logger.info(f"Pivot tables by {groupby_cols}")
    display(df_agg)
    display(df_pct_change)

2025-09-13 15:45:55,530 [2454748982.py:4] [INFO] Pivot tables by []

shape: (2, 11)
┌───────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Trap Game ┆ Sample Size ┆ GF       ┆ GA       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---       ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ bool      ┆ i32         ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ false     ┆ 2673        ┆ 3.27572  ┆ 2.575383 ┆ … ┆ 54.043471 ┆ 10.447995 ┆ 90.691938 ┆ 1.011404 │
│ true      ┆ 482         ┆ 3.475104 ┆ 2.522822 ┆ … ┆ 54.922676 ┆ 11.067282 ┆ 90.868071 ┆ 1.019342 │
└───────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (1, 10)
┌─────────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Sample Size ┆ GF       ┆ GA        ┆ GF%      ┆ … ┆ xGF%     ┆ SH%      ┆ SV%      ┆ PDO      │
│ ---         ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ -0.819678   ┆ 0.060867 ┆ -0.020409 ┆ 0.037863 ┆ … ┆ 0.016268 ┆ 0.059273 ┆ 0.001942 ┆ 0.007849 │
└─────────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

2025-09-13 15:45:55,550 [2454748982.py:4] [INFO] Pivot tables by ['Season']

shape: (36, 12)
┌────────┬───────────┬─────────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Season ┆ Trap Game ┆ Sample Size ┆ GF       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---    ┆ ---       ┆ ---         ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32    ┆ bool      ┆ i32         ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞════════╪═══════════╪═════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2008   ┆ false     ┆ 79          ┆ 2.962025 ┆ … ┆ 51.641667 ┆ 9.945696  ┆ 89.458101 ┆ 0.994013 │
│ 2008   ┆ true      ┆ 11          ┆ 2.272727 ┆ … ┆ 48.54     ┆ 8.218182  ┆ 91.112727 ┆ 0.993273 │
│ 2009   ┆ false     ┆ 132         ┆ 3.280303 ┆ … ┆ 54.231615 ┆ 10.397955 ┆ 89.906439 ┆ 1.00303  │
│ 2009   ┆ true      ┆ 24          ┆ 3.583333 ┆ … ┆ 55.09     ┆ 10.694167 ┆ 92.03375  ┆ 1.027292 │
│ 2010   ┆ false     ┆ 153         ┆ 3.202614 ┆ … ┆ 52.853595 ┆ 10.25902  ┆ 90.693203 ┆ 1.009549 │
│ …      ┆ …         ┆ …           ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2023   ┆ true      ┆ 40          ┆ 4.175    ┆ … ┆ 56.479    ┆ 13.00225  ┆ 89.90125  ┆ 1.02905  │
│ 2024   ┆ false     ┆ 163         ┆ 3.723926 ┆ … ┆ 55.17227  ┆ 11.577975 ┆ 90.44681  ┆ 1.020282 │
│ 2024   ┆ true      ┆ 24          ┆ 3.333333 ┆ … ┆ 61.899167 ┆ 10.362083 ┆ 89.84125  ┆ 1.002125 │
│ 2025   ┆ false     ┆ 222         ┆ 3.189189 ┆ … ┆ 53.647838 ┆ 11.133333 ┆ 89.468108 ┆ 1.006032 │
│ 2025   ┆ true      ┆ 47          ┆ 3.382979 ┆ … ┆ 54.734043 ┆ 12.331915 ┆ 89.130426 ┆ 1.014638 │
└────────┴───────────┴─────────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (18, 11)
┌────────┬─────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Season ┆ Sample Size ┆ GF        ┆ GA        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---    ┆ ---         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i32    ┆ f64         ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════╪═════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2008   ┆ -0.860759   ┆ -0.232712 ┆ -0.020661 ┆ … ┆ -0.060061 ┆ -0.173695 ┆ 0.018496  ┆ -0.000744 │
│ 2009   ┆ -0.818182   ┆ 0.092379  ┆ -0.186828 ┆ … ┆ 0.015828  ┆ 0.028488  ┆ 0.023661  ┆ 0.024188  │
│ 2010   ┆ -0.836601   ┆ 0.011673  ┆ 0.192615  ┆ … ┆ -0.022507 ┆ -0.006182 ┆ -0.010184 ┆ -0.009855 │
│ 2011   ┆ -0.869919   ┆ -0.04986  ┆ -0.143113 ┆ … ┆ 0.011585  ┆ 0.105414  ┆ 0.00807   ┆ 0.017185  │
│ 2012   ┆ -0.836207   ┆ 0.002882  ┆ 0.140776  ┆ … ┆ -0.011239 ┆ 0.027859  ┆ -0.011792 ┆ -0.008041 │
│ …      ┆ …           ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2021   ┆ -0.896373   ┆ -0.153253 ┆ -0.039089 ┆ … ┆ -0.029715 ┆ -0.165567 ┆ 0.012444  ┆ -0.006501 │
│ 2022   ┆ -0.666667   ┆ 0.157025  ┆ 0.026616  ┆ … ┆ 0.016959  ┆ 0.15304   ┆ -0.001347 ┆ 0.015106  │
│ 2023   ┆ -0.761905   ┆ 0.092523  ┆ 0.087411  ┆ … ┆ -0.022642 ┆ 0.126671  ┆ -0.005731 ┆ 0.009303  │
│ 2024   ┆ -0.852761   ┆ -0.104887 ┆ -0.02512  ┆ … ┆ 0.121925  ┆ -0.105018 ┆ -0.006695 ┆ -0.017796 │
│ 2025   ┆ -0.788288   ┆ 0.060765  ┆ -0.099577 ┆ … ┆ 0.020247  ┆ 0.107657  ┆ -0.003774 ┆ 0.008555  │
└────────┴─────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

2025-09-13 15:45:55,594 [2454748982.py:4] [INFO] Pivot tables by ['Team']

shape: (65, 12)
┌──────────────────────┬───────────┬─────────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Team                 ┆ Trap Game ┆ Sample Size ┆ GF       ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO      │
│ ---                  ┆ ---       ┆ ---         ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str                  ┆ bool      ┆ i32         ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════╪═════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Anaheim Ducks        ┆ false     ┆ 47          ┆ 3.170213 ┆ … ┆ 53.505745 ┆ 10.39766  ┆ 90.533404 ┆ 1.00934  │
│ Anaheim Ducks        ┆ true      ┆ 10          ┆ 2.5      ┆ … ┆ 54.578    ┆ 7.33      ┆ 89.976    ┆ 0.973    │
│ Atlanta Thrashers    ┆ false     ┆ 7           ┆ 3.285714 ┆ … ┆ 44.135714 ┆ 13.108571 ┆ 89.771429 ┆ 1.028857 │
│ Boston Bruins        ┆ false     ┆ 167         ┆ 3.281437 ┆ … ┆ 53.878144 ┆ 10.168743 ┆ 90.965808 ┆ 1.011353 │
│ Boston Bruins        ┆ true      ┆ 35          ┆ 3.342857 ┆ … ┆ 55.273429 ┆ 10.008286 ┆ 94.050571 ┆ 1.0406   │
│ …                    ┆ …         ┆ …           ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Vegas Golden Knights ┆ true      ┆ 18          ┆ 2.833333 ┆ … ┆ 51.740556 ┆ 10.036667 ┆ 89.192222 ┆ 0.992222 │
│ Washington Capitals  ┆ false     ┆ 165         ┆ 3.248485 ┆ … ┆ 52.225515 ┆ 10.612061 ┆ 89.957333 ┆ 1.005709 │
│ Washington Capitals  ┆ true      ┆ 30          ┆ 3.766667 ┆ … ┆ 51.794667 ┆ 12.459667 ┆ 92.197    ┆ 1.046533 │
│ Winnipeg Jets        ┆ false     ┆ 103         ┆ 3.019417 ┆ … ┆ 52.779806 ┆ 9.681165  ┆ 91.146796 ┆ 1.008282 │
│ Winnipeg Jets        ┆ true      ┆ 15          ┆ 3.866667 ┆ … ┆ 57.752    ┆ 12.328667 ┆ 88.284    ┆ 1.006067 │
└──────────────────────┴───────────┴─────────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (33, 11)
┌──────────────────────┬─────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Team                 ┆ Sample Size ┆ GF        ┆ GA        ┆ … ┆ xGF%      ┆ SH%       ┆ SV%       ┆ PDO       │
│ ---                  ┆ ---         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str                  ┆ f64         ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════════════════╪═════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Anaheim Ducks        ┆ -0.787234   ┆ -0.211409 ┆ -0.014516 ┆ … ┆ 0.02004   ┆ -0.295034 ┆ -0.006157 ┆ -0.036004 │
│ Atlanta Thrashers    ┆ null        ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ Boston Bruins        ┆ -0.790419   ┆ 0.018717  ┆ -0.347305 ┆ … ┆ 0.025897  ┆ -0.015779 ┆ 0.033911  ┆ 0.028918  │
│ Buffalo Sabres       ┆ -0.92       ┆ 0.029412  ┆ 0.008065  ┆ … ┆ -0.172712 ┆ 0.129079  ┆ 0.014869  ┆ 0.027668  │
│ Calgary Flames       ┆ -0.796296   ┆ 0.029712  ┆ -0.217391 ┆ … ┆ 0.006682  ┆ -0.014185 ┆ 0.023569  ┆ 0.019165  │
│ …                    ┆ …           ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Toronto Maple Leafs  ┆ -0.785714   ┆ 0.031826  ┆ -0.11976  ┆ … ┆ 0.008986  ┆ 0.063838  ┆ 0.013034  ┆ 0.0186    │
│ Vancouver Canucks    ┆ -0.918367   ┆ -0.222222 ┆ -0.001073 ┆ … ┆ -0.011934 ┆ -0.255652 ┆ 0.006038  ┆ -0.021698 │
│ Vegas Golden Knights ┆ -0.772152   ┆ -0.21462  ┆ 0.145868  ┆ … ┆ -0.052637 ┆ -0.080678 ┆ -0.015965 ┆ -0.023014 │
│ Washington Capitals  ┆ -0.818182   ┆ 0.159515  ┆ -0.180851 ┆ … ┆ -0.00825  ┆ 0.174104  ┆ 0.024897  ┆ 0.040592  │
│ Winnipeg Jets        ┆ -0.854369   ┆ 0.2806    ┆ 0.170455  ┆ … ┆ 0.094206  ┆ 0.273469  ┆ -0.031409 ┆ -0.002197 │
└──────────────────────┴─────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘